name: dev-supabase-db-migrate

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 1.169.8
      - run: supabase db start
      - run: supabase db lint
  migrate:
    needs: lint
    runs-on: ubuntu-22.04
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.DEV_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DEV_SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.DEV_SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 1.169.8
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push --dry-run
      - run: supabase db push
